version: '2'
services:
  web:
    build: server
    ports:
      - "3000:3000"
    volumes:
      - .:/app
  redis:
    build: redis
    env_file: .env
    ports:
      - "26379:6379"
  postgres:
    build: postgres
    env_file: .env
    ports:
      - "25432:5432"
